#!/usr/bin/env bash
# 08 - Write the application .env from the values in config.env.
set -euo pipefail
cd "$(dirname "$0")"
source ./config.env

REPO_ROOT="$(cd .. && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

if [ -f "${ENV_FILE}" ]; then
  cp "${ENV_FILE}" "${ENV_FILE}.bak"
  echo "Backed up existing .env to .env.bak"
fi

cat > "${ENV_FILE}" <<EOF
# Generated by deploy/08_write_env.sh
# Self-hosted NIM (tried first)
NIM_BASE_URL=http://${SERVICE_HOST}:${NIM_SUPERVISOR_PORT}/v1
NIM_MODEL=${NIM_MODEL}
NIM_SUBAGENT_MODEL=${NIM_SUBAGENT_MODEL}
NIM_API_KEY=

# NVIDIA cloud NIM (used automatically when the self-hosted NIM is unreachable)
NIM_CLOUD_FALLBACK=${NIM_CLOUD_FALLBACK}
NIM_CLOUD_BASE_URL=${NIM_CLOUD_BASE_URL}
NIM_CLOUD_MODEL=${NIM_CLOUD_MODEL}
NIM_CLOUD_API_KEY=${NIM_CLOUD_API_KEY}

# Production service endpoints
CUOPT_URL=http://${SERVICE_HOST}:${CUOPT_ADAPTER_PORT}
NEMO_GUARDRAILS_URL=http://${SERVICE_HOST}:${GUARDRAILS_PORT}
OPENSHELL_URL=http://${SERVICE_HOST}:${OPENSHELL_PORT}

# Enterprise data endpoints
WMS_URL=${WMS_URL}
ERP_URL=${ERP_URL}
FORECAST_URL=${FORECAST_URL}

# Workflow settings
APPROVAL_STORE=results/approvals.json
AGENT_REQUEST_TIMEOUT_SECONDS=60
AGENT_DRY_RUN=true
EOF

echo "Wrote ${ENV_FILE}"
echo
echo "Stale shell exports would otherwise shadow this file, so clear them:"
echo "  unset NIM_BASE_URL NIM_MODEL NIM_API_KEY NEMO_GUARDRAILS_URL CUOPT_URL RAIL_API_URL LLM_NIM_URL"
echo
echo "Next: ./09_healthcheck.sh"
